{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubeatlas.fullname" . }}
  labels:
    {{- include "kubeatlas.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host | default (printf "%s.%s" (include "kubeatlas.fullname" .) .Values.global.domain) }}
  to:
    kind: Service
    name: {{ include "kubeatlas.fullname" . }}-ui
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.route.tls.certificate }}
    certificate: |
      {{- .Values.route.tls.certificate | nindent 6 }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: |
      {{- .Values.route.tls.key | nindent 6 }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: |
      {{- .Values.route.tls.caCertificate | nindent 6 }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
