apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeatlas.fullname" . }}-api
  labels:
    {{- include "kubeatlas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeatlas.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeatlas.fullname" . }}-ui
  labels:
    {{- include "kubeatlas.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeatlas.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
